[package]
name = "mercado-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.4.9", features = ["csr"] }
leptos_router = { version = "0.4.9", features = ["csr"]}
mercado = { path = "../mercado", features = ["client"], default-features = false }
anyhow = "1.0"

